name: 'Create Draft Release'

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'
      - name: Monorepo install
        uses: ./.github/actions/yarn-nm-install
      - name: Check security dependencies
        uses: ./.github/actions/security/lockfile
        with:
          path: 'yarn.lock'
          type: 'yarn'
          allowedHosts: 'https://registry.npmjs.org'
          allowedURLs: ''
      - name: Create Draft Release Packages
        run: bash ./scripts/create-draft-release.sh
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
