name: Tests Workflow

on:
  push:
    branches: [master]
  pull_request:
    branches: [master, development]
    paths-ignore:
      - 'docs/**'
      - '**.mdx?'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

permissions:
  contents: read
  actions: read

jobs:
  all-in-one:
    name: 'All-in-one (node: 18)'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Monorepo install
        run: ./.github/actions/yarn-nm-install
      - name: Monorepo build
        run: ./.github/actions/run-build
      - name: Monorepo lint
        run: ./.github/actions/run-lints
      - name: Monorepo tests
        run: ./.github/actions/run-unit-tests
